'use client'

import { HugeiconsIcon } from '@hugeicons/react'
import type { IconSvgElement } from '@hugeicons/react'
import {
  AiBeautifyIcon,
  AiBrain01Icon,
  AiIdeaIcon,
  AiImageIcon,
  AiInnovation01Icon,
  AiMagicIcon,
  AiMicIcon,
  AiSearchIcon,
  AiSecurity01Icon,
  AiViewIcon,
  AiVideoIcon,
  Alert01Icon,
  Analytics01Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowShrink01Icon,
  ArrowTurnDownIcon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  BarChartIcon,
  Book01Icon,
  BubbleChatIcon,
  Building01Icon,
  BulbIcon,
  Calendar01Icon,
  Camera01Icon,
  Cancel01Icon,
  Chat01Icon,
  ChatBotIcon,
  CheckmarkCircle01Icon,
  CircleIcon,
  ClipboardIcon,
  Clock01Icon,
  CodeIcon,
  Coffee01Icon,
  CommandLineIcon,
  Comment01Icon,
  ComputerIcon,
  CookieIcon,
  Database01Icon,
  Delete01Icon,
  DiamondIcon,
  DnaIcon,
  Download01Icon,
  DropletIcon,
  Edit01Icon,
  EyeIcon,
  File01Icon,
  Film01Icon,
  FireIcon,
  Flag01Icon,
  FlashIcon,
  Folder01Icon,
  FolderLibraryIcon,
  FolderOpenIcon,
  GiftIcon,
  GitBranchIcon,
  GithubIcon,
  GlobeIcon,
  GridIcon,
  HeartbreakIcon,
  HelpCircleIcon,
  HexagonIcon,
  Home01Icon,
  HourglassIcon,
  Image01Icon,
  InformationCircleIcon,
  Key01Icon,
  KeyboardIcon,
  LaptopIcon,
  LayoutGridIcon,
  Leaf01Icon,
  Link01Icon,
  LockIcon,
  Mail01Icon,
  MagicWand01Icon,
  Medal01Icon,
  Megaphone01Icon,
  Menu01Icon,
  MicroscopeIcon,
  MoreIcon,
  Mouse01Icon,
  MusicNote01Icon,
  Package01Icon,
  PartyIcon,
  PauseIcon,
  Pen01Icon,
  PenTool01Icon,
  PieChartIcon,
  PinIcon,
  Plant01Icon,
  PlayIcon,
  Plug01Icon,
  PuzzleIcon,
  QuestionIcon,
  Radar01Icon,
  RefreshIcon,
  RoadIcon,
  Robot01Icon,
  Rocket01Icon,
  Rotate01Icon,
  SatelliteIcon,
  ScanIcon,
  Scroll01Icon,
  ScrollIcon,
  Search01Icon,
  ServerStack01Icon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SparklesIcon,
  Speaker01Icon,
  SquareIcon,
  StarCircleIcon,
  StarIcon,
  Target01Icon,
  Tag01Icon,
  TestTube01Icon,
  ThumbsUpIcon,
  ToolsIcon,
  TriangleIcon,
  UmbrellaIcon,
  UndoIcon,
  Upload01Icon,
  UserGroupIcon,
  UserIcon,
  ViewIcon,
  VoiceIcon,
  VolumeHighIcon,
  WaveIcon,
  Wifi01Icon,
  Wrench01Icon,
} from '@hugeicons/core-free-icons'

/**
 * 品牌龙虾图标（Hugeicons 无龙虾，手绘风格化轮廓，随 currentColor 变色）。
 * 用于 agent-avatar、loading-indicator、设置页等 🦞 品牌位。
 */
export function LobsterIcon({
  className,
  size = 16,
}: {
  className?: string
  size?: number
}) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={1.6}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className={className}
    >
      {/* 触须 */}
      <path d="M8.5 6.4C7 3.9 5.1 2.7 2.9 2.2" />
      <path d="M15.5 6.4C17 3.9 18.9 2.7 21.1 2.2" />
      {/* 大螯 */}
      <path d="M5.6 9.6C3.2 9.1 1.7 10.5 2.1 13c.4 2.5 2.4 3.9 4.5 3.1.3-1.5.1-4.2-1-6.5Z" />
      <path d="M18.4 9.6c2.4-.5 3.9.9 3.5 3.4-.4 2.5-2.4 3.9-4.5 3.1-.3-1.5-.1-4.2 1-6.5Z" />
      {/* 头胸部 */}
      <path d="M9 5.6h6v8.4c0 2.2-1.3 3.5-3 3.5s-3-1.3-3-3.5V5.6Z" />
      {/* 尾扇 */}
      <path d="M12 17.5c-1.4.4-2.3 1.4-2.7 2.8M12 17.5c1.4.4 2.3 1.4 2.7 2.8M12 17.5c0 1.8.7 3 1.7 3.8M12 17.5c0 1.8-.7 3-1.7 3.8" />
      {/* 步足 */}
      <path d="M9 10.2c-1.6-.2-2.9.2-3.8 1.2M9 12.7c-1.8.2-3.1.9-3.9 2.1M15 10.2c1.6-.2 2.9.2 3.8 1.2M15 12.7c1.8.2 3.1.9 3.9 2.1" />
    </svg>
  )
}

/** emoji 字符 → Hugeicons 图标（未收录的 emoji 归入 fallback 图标） */
const EMOJI_ICON_MAP: Record<string, IconSvgElement> = {
  '⚠': Alert01Icon,
  '⚠️': Alert01Icon,
  '✅': CheckmarkCircle01Icon,
  '❌': Cancel01Icon,
  '✓': CheckmarkCircle01Icon,
  '✗': Cancel01Icon,
  '✕': Cancel01Icon,
  '⚕': AiBrain01Icon,
  '🔍': Search01Icon,
  '🔎': AiSearchIcon,
  '💬': Chat01Icon,
  '📁': Folder01Icon,
  '📂': FolderOpenIcon,
  '🤖': ChatBotIcon,
  '🛠️': ToolsIcon,
  '🔧': Wrench01Icon,
  '🏗️': Building01Icon,
  '📣': Megaphone01Icon,
  '🚀': Rocket01Icon,
  '📊': BarChartIcon,
  '✍️': Pen01Icon,
  '🔐': LockIcon,
  '📱': SmartPhone01Icon,
  '🌐': GlobeIcon,
  '💻': ComputerIcon,
  '🗂️': FolderLibraryIcon,
  '🔮': StarCircleIcon,
  '🖱': Mouse01Icon,
  '⌨': KeyboardIcon,
  '⏎': ArrowTurnDownIcon,
  '↕': ArrowUpDownIcon,
  '←': ArrowLeft01Icon,
  '🖼': AiImageIcon,
  '👁': ViewIcon,
  '☑': CheckmarkCircle01Icon,
  '⏰': Clock01Icon,
  '👥': UserGroupIcon,
  '🧠': AiBrain01Icon,
  '❓': QuestionIcon,
  '📦': Package01Icon,
  '🔊': VolumeHighIcon,
  '👤': UserIcon,
  '📋': ClipboardIcon,
  '🏠': Home01Icon,
  '📄': File01Icon,
  '📸': Camera01Icon,
  '📖': Book01Icon,
  '🗣️': VoiceIcon,
  '▾': ArrowDown01Icon,
  '▸': ArrowRight01Icon,
  '▶': PlayIcon,
  '⏸️': PauseIcon,
  '💭': BubbleChatIcon,
  '↩️': UndoIcon,
  '🗑️': Delete01Icon,
  '✏️': Pen01Icon,
  '🔄': RefreshIcon,
  '✉️': Mail01Icon,
  '⏳': HourglassIcon,
  '🛒': ShoppingCart01Icon,
  '🙆': UserIcon,
  '🏢': Building01Icon,
  '⬇️': Download01Icon,
  '📡': SatelliteIcon,
  '🗄️': Database01Icon,
  '🖥️': ComputerIcon,
  '📃': Scroll01Icon,
  '📜': ScrollIcon,
  '🔷': DiamondIcon,
  '🔶': DiamondIcon,
  '◐': CircleIcon,
  '◆': DiamondIcon,
  '◈': HexagonIcon,
  '🗜️': ArrowShrink01Icon,
  '🆕': AiInnovation01Icon,
  '💡': AiIdeaIcon,
  '🔌': Plug01Icon,
  '🎉': PartyIcon,
  '🔗': Link01Icon,
  '📐': TriangleIcon,
  '📞': SmartPhone01Icon,
  '📤': Upload01Icon,
  '💾': Download01Icon,
  '↻': Rotate01Icon,
  '↺': RefreshIcon,
  '▲': ArrowUp01Icon,
  '▼': ArrowDown01Icon,
  '↑': ArrowUp01Icon,
  '↓': ArrowDown01Icon,
  '↗': ArrowUpRight01Icon,
  '●': CircleIcon,
  '○': CircleIcon,
  '⊞': GridIcon,
  '⚙': Settings01Icon,
  '🔔': InformationCircleIcon,
  '📅': Calendar01Icon,
  '🏷️': Tag01Icon,
  '🗺️': PinIcon,
  '✎': Pen01Icon,
  '⏭️': ArrowRight01Icon,
  '⏮️': ArrowLeft01Icon,
  '❤️': ThumbsUpIcon,
  '💯': Medal01Icon,
  '👑': StarIcon,
  '🤝': Share01Icon,
  '✋': Share01Icon,
  '👋': Share01Icon,
  '👍': ThumbsUpIcon,
  '👎': ThumbsUpIcon,
  '👏': ThumbsUpIcon,
  '🙏': ThumbsUpIcon,
  '💪': ThumbsUpIcon,
  '💔': HeartbreakIcon,
  '🔑': Key01Icon,
  '🛡': Shield01Icon,
  '💎': DiamondIcon,
  '🖨️': ComputerIcon,
  '🔋': FlashIcon,
  '📶': Wifi01Icon,
  '🆙': ArrowUp01Icon,
  '🆓': GiftIcon,
  '🗃️': Database01Icon,
  '📫': Mail01Icon,
  '📮': Mail01Icon,
  '🖌️': PenTool01Icon,
  '🖊️': Pen01Icon,
  '🗒️': ClipboardIcon,
  '🗓️': Calendar01Icon,
  '🚦': Flag01Icon,
  '🚩': Flag01Icon,
  '🏁': Flag01Icon,
  '⚓': PinIcon,
  '🧲': Link01Icon,
  '🧪': TestTube01Icon,
  '🧫': MicroscopeIcon,
  '🧬': DnaIcon,
  '🔬': MicroscopeIcon,
  '🔭': MicroscopeIcon,
  '🛰️': SatelliteIcon,
  '🛸': SatelliteIcon,
  '✈️': Rocket01Icon,
  '🚁': Rocket01Icon,
  '🚂': Rocket01Icon,
  '🚃': Rocket01Icon,
  '🚄': Rocket01Icon,
  '🚅': Rocket01Icon,
  '🚆': Rocket01Icon,
  '🚇': Rocket01Icon,
  '🚈': Rocket01Icon,
  '🚉': Rocket01Icon,
  '🚊': Rocket01Icon,
  '🚋': Rocket01Icon,
  '🚌': Rocket01Icon,
  '🚍': Rocket01Icon,
  '🚎': Rocket01Icon,
  '🚏': PinIcon,
  '🚐': Rocket01Icon,
  '🚑': Rocket01Icon,
  '🚒': FireIcon,
  '🚓': Rocket01Icon,
  '🚔': Rocket01Icon,
  '🚕': Rocket01Icon,
  '🚖': Rocket01Icon,
  '🚗': Rocket01Icon,
  '🚘': Rocket01Icon,
  '🚙': Rocket01Icon,
  '🚚': Rocket01Icon,
  '🚛': Rocket01Icon,
  '🚜': Rocket01Icon,
  '🚝': Rocket01Icon,
  '🚞': Rocket01Icon,
  '🚟': Rocket01Icon,
  '🚠': Rocket01Icon,
  '🚡': Rocket01Icon,
  '🚢': Rocket01Icon,
  '🚤': Rocket01Icon,
  '🛥️': Rocket01Icon,
  '🛳️': Rocket01Icon,
  '⛴️': Rocket01Icon,
  '🛶': Rocket01Icon,
  '⛺': Home01Icon,
  '🏕️': Home01Icon,
  '🏖️': Camera01Icon,
  '🏜️': Camera01Icon,
  '🏝️': Camera01Icon,
  '🏔️': TriangleIcon,
  '⛰️': TriangleIcon,
  '🌋': FireIcon,
  '🗻': TriangleIcon,
  '🏞️': Plant01Icon,
  '🛣️': RoadIcon,
  '🛤️': RoadIcon,
  '🌄': StarIcon,
  '🌅': StarIcon,
  '🌇': Building01Icon,
  '🌆': Building01Icon,
  '🌃': Building01Icon,
  '🌉': Link01Icon,
  '🎠': PlayIcon,
  '🎡': Rotate01Icon,
  '🎢': PlayIcon,
  '💈': Flag01Icon,
  '🎰': PlayIcon,
  '🧩': PuzzleIcon,
  '🎴': PlayIcon,
  '🃏': PlayIcon,
  '🎀': GiftIcon,
  '🎁': GiftIcon,
  '🏵️': Medal01Icon,
  '🎓': Book01Icon,
  '🦸': StarIcon,
  '🦹': StarIcon,
  '🧙': MagicWand01Icon,
  '🧚': SparklesIcon,
  '🧛': MoreIcon,
  '🧜': WaveIcon,
  '🧝': Leaf01Icon,
  '🧞': SparklesIcon,
  '🧟': MoreIcon,
  '💆': UserIcon,
  '💇': UserIcon,
  '🚶': UserIcon,
  '🏃': UserIcon,
  '💃': UserIcon,
  '🕺': UserIcon,
  '🕴️': UserIcon,
  '👯': UserGroupIcon,
  '🧖': UserIcon,
  '🤹': SparklesIcon,
  '🛀': DropletIcon,
  '🛌': Home01Icon,
  '👪': UserGroupIcon,
  '💑': UserGroupIcon,
  '💏': UserGroupIcon,
  '👩‍❤️‍👨': UserGroupIcon,
  '👨‍❤️‍👨': UserGroupIcon,
  '👩‍❤️‍👩': UserGroupIcon,
  '👩‍❤️‍💋‍👨': UserGroupIcon,
  '👨‍❤️‍💋‍👨': UserGroupIcon,
  '👩‍❤️‍💋‍👩': UserGroupIcon,
  '👨‍👩‍👦': UserGroupIcon,
  '👨‍👩‍👧': UserGroupIcon,
  '👨‍👩‍👧‍👦': UserGroupIcon,
  '👨‍👩‍👦‍👦': UserGroupIcon,
  '👨‍👩‍👧‍👧': UserGroupIcon,
  '👨‍👨‍👦': UserGroupIcon,
  '👨‍👨‍👧': UserGroupIcon,
  '👨‍👨‍👧‍👦': UserGroupIcon,
  '👨‍👨‍👦‍👦': UserGroupIcon,
  '👨‍👨‍👧‍👧': UserGroupIcon,
  '👩‍👩‍👦': UserGroupIcon,
  '👩‍👩‍👧': UserGroupIcon,
  '👩‍👩‍👧‍👦': UserGroupIcon,
  '👩‍👩‍👦‍👦': UserGroupIcon,
  '👩‍👩‍👧‍👧': UserGroupIcon,
  '👨‍👦': UserGroupIcon,
  '👨‍👦‍👦': UserGroupIcon,
  '👨‍👧': UserGroupIcon,
  '👨‍👧‍👦': UserGroupIcon,
  '👨‍👧‍👧': UserGroupIcon,
  '👩‍👦': UserGroupIcon,
  '👩‍👦‍👦': UserGroupIcon,
  '👩‍👧': UserGroupIcon,
  '👩‍👧‍👦': UserGroupIcon,
  '👩‍👧‍👧': UserGroupIcon,
  '🧓': UserIcon,
  '👴': UserIcon,
  '👵': UserIcon,
  '👶': UserIcon,
  '🧒': UserIcon,
  '👦': UserIcon,
  '👧': UserIcon,
  '🧕': UserIcon,
  '👲': UserIcon,
  '👳': UserIcon,
  '👮': Shield01Icon,
  '👷': ToolsIcon,
  '💂': Shield01Icon,
  '🕵️': Search01Icon,
  '👩‍✈️': Rocket01Icon,
  '👨‍✈️': Rocket01Icon,
  '🧑‍✈️': Rocket01Icon,
  '👩‍🚀': Rocket01Icon,
  '👨‍🚀': Rocket01Icon,
  '🧑‍🚀': Rocket01Icon,
  '👩‍🚒': FireIcon,
  '👨‍🚒': FireIcon,
  '🧑‍🚒': FireIcon,
  '👩‍⚕️': AiBrain01Icon,
  '👨‍⚕️': AiBrain01Icon,
  '🧑‍⚕️': AiBrain01Icon,
  '👩‍⚖️': Flag01Icon,
  '👨‍⚖️': Flag01Icon,
  '🧑‍⚖️': Flag01Icon,
  '👩‍🌾': Plant01Icon,
  '👨‍🌾': Plant01Icon,
  '🧑‍🌾': Plant01Icon,
  '👩‍🍳': CookieIcon,
  '👨‍🍳': CookieIcon,
  '🧑‍🍳': CookieIcon,
  '👩‍🎤': AiMicIcon,
  '👨‍🎤': AiMicIcon,
  '🧑‍🎤': AiMicIcon,
  '👩‍💻': ComputerIcon,
  '👨‍💻': ComputerIcon,
  '🧑‍💻': ComputerIcon,
  '👩‍🏫': Book01Icon,
  '👨‍🏫': Book01Icon,
  '🧑‍🏫': Book01Icon,
  '👩‍💼': UserIcon,
  '👨‍💼': UserIcon,
  '🧑‍💼': UserIcon,
  '👩‍🔧': ToolsIcon,
  '👨‍🔧': ToolsIcon,
  '🧑‍🔧': ToolsIcon,
  '👩‍🔬': MicroscopeIcon,
  '👨‍🔬': MicroscopeIcon,
  '🧑‍🔬': MicroscopeIcon,
  '👩‍🎨': AiBeautifyIcon,
  '👨‍🎨': AiBeautifyIcon,
  '🧑‍🎨': AiBeautifyIcon,
  '👩‍🏭': ToolsIcon,
  '👨‍🏭': ToolsIcon,
  '🧑‍🏭': ToolsIcon,
  '👩‍🎓': Book01Icon,
  '👨‍🎓': Book01Icon,
  '🧑‍🎓': Book01Icon,
  '🦸‍♀️': StarIcon,
  '🦸‍♂️': StarIcon,
  '🦹‍♀️': StarIcon,
  '🦹‍♂️': StarIcon,
  '🧙‍♀️': MagicWand01Icon,
  '🧙‍♂️': MagicWand01Icon,
  '🧚‍♀️': SparklesIcon,
  '🧚‍♂️': SparklesIcon,
  '🧛‍♀️': MoreIcon,
  '🧛‍♂️': MoreIcon,
  '🧜‍♀️': WaveIcon,
  '🧜‍♂️': WaveIcon,
  '🧝‍♀️': Leaf01Icon,
  '🧝‍♂️': Leaf01Icon,
  '🧞‍♀️': SparklesIcon,
  '🧞‍♂️': SparklesIcon,
  '🧟‍♀️': MoreIcon,
  '🧟‍♂️': MoreIcon,
  '👩‍🦰': UserIcon,
  '👨‍🦰': UserIcon,
  '👩‍🦱': UserIcon,
  '👨‍🦱': UserIcon,
  '👩‍🦳': UserIcon,
  '👨‍🦳': UserIcon,
  '👩‍🦲': UserIcon,
  '👨‍🦲': UserIcon,
  '👩‍🦽': UserIcon,
  '👨‍🦽': UserIcon,
  '👩‍🦼': UserIcon,
  '👨‍🦼': UserIcon,
  '👩‍🦯': UserIcon,
  '👨‍🦯': UserIcon,
  '🐶': Mouse01Icon,
  '🐱': Mouse01Icon,
  '🐭': Mouse01Icon,
  '🐹': Mouse01Icon,
  '🐰': Mouse01Icon,
  '🦊': Mouse01Icon,
  '🐻': Mouse01Icon,
  '🐼': Mouse01Icon,
  '🐨': Mouse01Icon,
  '🐯': Mouse01Icon,
  '🦁': Mouse01Icon,
  '🐮': Mouse01Icon,
  '🐷': Mouse01Icon,
  '🐽': Mouse01Icon,
  '🐸': Mouse01Icon,
  '🐵': Mouse01Icon,
  '🙈': ViewIcon,
  '🙉': ViewIcon,
  '🙊': ViewIcon,
  '🐒': Mouse01Icon,
  '🐔': Mouse01Icon,
  '🐧': Mouse01Icon,
  '🐦': Mouse01Icon,
  '🐤': Mouse01Icon,
  '🐣': Mouse01Icon,
  '🐥': Mouse01Icon,
  '🦆': Mouse01Icon,
  '🦅': Rocket01Icon,
  '🦉': Mouse01Icon,
  '🦇': Mouse01Icon,
  '🐺': Mouse01Icon,
  '🐗': Mouse01Icon,
  '🐴': Mouse01Icon,
  '🦄': SparklesIcon,
  '🐝': FlashIcon,
  '🐛': Mouse01Icon,
  '🦋': SparklesIcon,
  '🐌': Rotate01Icon,
  '🐞': Mouse01Icon,
  '🐜': Mouse01Icon,
  '🪰': MoreIcon,
  '🪲': Mouse01Icon,
  '🦟': MoreIcon,
  '🦗': Mouse01Icon,
  '🕷️': MoreIcon,
  '🕸️': MoreIcon,
  '🦂': MoreIcon,
  '🐢': Rotate01Icon,
  '🐍': CodeIcon,
  '🦎': Mouse01Icon,
  '🦖': MoreIcon,
  '🦕': MoreIcon,
  '🐙': GithubIcon,
  '🦑': WaveIcon,
  '🦐': WaveIcon,
  '🦞': SquareIcon,
  '🦀': WaveIcon,
  '🐡': WaveIcon,
  '🐠': WaveIcon,
  '🐟': WaveIcon,
  '🐬': WaveIcon,
  '🐳': WaveIcon,
  '🐋': WaveIcon,
  '🦈': WaveIcon,
  '🐊': Mouse01Icon,
  '🐅': Mouse01Icon,
  '🐆': Mouse01Icon,
  '🦓': Mouse01Icon,
  '🦍': Mouse01Icon,
  '🦧': Mouse01Icon,
  '🦣': Mouse01Icon,
  '🐘': Mouse01Icon,
  '🦛': Mouse01Icon,
  '🦏': Mouse01Icon,
  '🐪': Mouse01Icon,
  '🐫': Mouse01Icon,
  '🦒': Mouse01Icon,
  '🦘': Mouse01Icon,
  '🐃': Mouse01Icon,
  '🐂': Mouse01Icon,
  '🐄': Mouse01Icon,
  '🐎': Mouse01Icon,
  '🐖': Mouse01Icon,
  '🐏': Mouse01Icon,
  '🐑': Mouse01Icon,
  '🦙': Mouse01Icon,
  '🐐': Mouse01Icon,
  '🦌': Mouse01Icon,
  '🐕': Mouse01Icon,
  '🐩': Mouse01Icon,
  '🦮': Mouse01Icon,
  '🐈': Mouse01Icon,
  '🐓': Mouse01Icon,
  '🦃': Mouse01Icon,
  '🦤': Mouse01Icon,
  '🦚': SparklesIcon,
  '🦜': Mouse01Icon,
  '🦢': Mouse01Icon,
  '🦩': Mouse01Icon,
  '🕊️': Rocket01Icon,
  '🐇': Mouse01Icon,
  '🦝': Mouse01Icon,
  '🦨': Mouse01Icon,
  '🦡': Mouse01Icon,
  '🦫': Mouse01Icon,
  '🦦': Mouse01Icon,
  '🦥': Mouse01Icon,
  '🐁': Mouse01Icon,
  '🐀': Mouse01Icon,
  '🐿️': Mouse01Icon,
  '🦔': Mouse01Icon,
  '🐾': Mouse01Icon,
  '🐉': MoreIcon,
  '🐲': MoreIcon,
  '🌵': Plant01Icon,
  '🎄': Plant01Icon,
  '🌲': Plant01Icon,
  '🌳': Plant01Icon,
  '🌴': Plant01Icon,
  '🌱': Plant01Icon,
  '🌿': Leaf01Icon,
  '☘️': Leaf01Icon,
  '🍀': Leaf01Icon,
  '🎍': Plant01Icon,
  '🎋': Plant01Icon,
  '🍃': Leaf01Icon,
  '🍂': Leaf01Icon,
  '🍁': Leaf01Icon,
  '🍄': MoreIcon,
  '🌾': Plant01Icon,
  '💐': GiftIcon,
  '🌷': Plant01Icon,
  '🌹': Plant01Icon,
  '🥀': Plant01Icon,
  '🌺': Plant01Icon,
  '🌸': Plant01Icon,
  '🌼': Plant01Icon,
  '🌻': Plant01Icon,
  '🌞': StarIcon,
  '🌝': StarIcon,
  '🌛': CircleIcon,
  '🌜': CircleIcon,
  '🌚': CircleIcon,
  '🌕': CircleIcon,
  '🌖': CircleIcon,
  '🌗': CircleIcon,
  '🌘': CircleIcon,
  '🌑': CircleIcon,
  '🌒': CircleIcon,
  '🌓': CircleIcon,
  '🌔': CircleIcon,
  '🌙': CircleIcon,
  '🌎': GlobeIcon,
  '🌍': GlobeIcon,
  '🌏': GlobeIcon,
  '🪐': StarCircleIcon,
  '💫': SparklesIcon,
  '⭐': StarIcon,
  '🌟': StarIcon,
  '✨': MagicWand01Icon,
  '☄️': Rocket01Icon,
  '💥': FlashIcon,
  '🌪️': Rotate01Icon,
  '🌈': SparklesIcon,
  '☀️': StarIcon,
  '🌤️': StarIcon,
  '⛅': StarIcon,
  '🌥️': StarIcon,
  '☁️': CircleIcon,
  '🌦️': DropletIcon,
  '🌧️': DropletIcon,
  '⛈️': FlashIcon,
  '🌨️': DropletIcon,
  '❄️': StarIcon,
  '☃️': StarIcon,
  '⛄': StarIcon,
  '🌬️': WaveIcon,
  '🌀': Rotate01Icon,
  '🌫️': MoreIcon,
  '☂️': UmbrellaIcon,
  '☔': DropletIcon,
  '⛱️': DropletIcon,
  '⚡': FlashIcon,
  '🔥': FireIcon,
  '💧': DropletIcon,
  '🌊': WaveIcon,
  '🍎': Plant01Icon,
  '🍐': Plant01Icon,
  '🍊': Plant01Icon,
  '🍋': Plant01Icon,
  '🍌': Plant01Icon,
  '🍉': Plant01Icon,
  '🍇': Plant01Icon,
  '🍓': Plant01Icon,
  '🫐': Plant01Icon,
  '🍈': Plant01Icon,
  '🍒': Plant01Icon,
  '🍑': Plant01Icon,
  '🥭': Plant01Icon,
  '🍍': Plant01Icon,
  '🥥': Plant01Icon,
  '🥝': Plant01Icon,
  '🍅': Plant01Icon,
  '🥑': Plant01Icon,
  '🥦': Plant01Icon,
  '🥬': Plant01Icon,
  '🥒': Plant01Icon,
  '🌶️': FireIcon,
  '🫑': Plant01Icon,
  '🌽': Plant01Icon,
  '🥕': Plant01Icon,
  '🧄': Plant01Icon,
  '🧅': Plant01Icon,
  '🥔': Plant01Icon,
  '🍠': Plant01Icon,
  '🥐': CookieIcon,
  '🥯': CookieIcon,
  '🍞': CookieIcon,
  '🥖': CookieIcon,
  '🥨': CookieIcon,
  '🧀': CookieIcon,
  '🥚': CircleIcon,
  '🍳': CookieIcon,
  '🧈': CircleIcon,
  '🥞': CookieIcon,
  '🧇': CookieIcon,
  '🥓': CookieIcon,
  '🥩': CookieIcon,
  '🍗': CookieIcon,
  '🍖': CookieIcon,
  '🌭': CookieIcon,
  '🍔': CookieIcon,
  '🍟': CookieIcon,
  '🍕': CookieIcon,
  '🫓': CookieIcon,
  '🥪': CookieIcon,
  '🥙': CookieIcon,
  '🧆': CookieIcon,
  '🌮': CookieIcon,
  '🌯': CookieIcon,
  '🫔': CookieIcon,
  '🥗': Plant01Icon,
  '🥘': CookieIcon,
  '🫕': CookieIcon,
  '🥫': Package01Icon,
  '🍝': CookieIcon,
  '🍜': CookieIcon,
  '🍲': CookieIcon,
  '🍛': CookieIcon,
  '🍣': CookieIcon,
  '🍱': CookieIcon,
  '🥟': CookieIcon,
  '🦪': WaveIcon,
  '🍤': WaveIcon,
  '🍙': CookieIcon,
  '🍚': CookieIcon,
  '🍘': CookieIcon,
  '🍥': CookieIcon,
  '🥠': CookieIcon,
  '🥮': CookieIcon,
  '🍢': CookieIcon,
  '🍡': CookieIcon,
  '🍧': CookieIcon,
  '🍨': CookieIcon,
  '🍦': CookieIcon,
  '🥧': CookieIcon,
  '🧁': CookieIcon,
  '🍰': CookieIcon,
  '🎂': PartyIcon,
  '🍮': CookieIcon,
  '🍭': CookieIcon,
  '🍬': CookieIcon,
  '🍫': CookieIcon,
  '🍿': CookieIcon,
  '🍩': CookieIcon,
  '🍪': CookieIcon,
  '🌰': CookieIcon,
  '🥜': CookieIcon,
  '🍯': DropletIcon,
  '🥛': DropletIcon,
  '🍼': DropletIcon,
  '☕': Coffee01Icon,
  '🫖': Coffee01Icon,
  '🍵': Coffee01Icon,
  '🧉': Coffee01Icon,
  '🧃': DropletIcon,
  '🥤': DropletIcon,
  '🧋': DropletIcon,
  '🍶': DropletIcon,
  '🍺': DropletIcon,
  '🍻': DropletIcon,
  '🥂': DropletIcon,
  '🍷': DropletIcon,
  '🥃': DropletIcon,
  '🍸': DropletIcon,
  '🍹': DropletIcon,
  '🍾': DropletIcon,
  '🥄': MoreIcon,
  '🍴': MoreIcon,
  '🍽️': MoreIcon,
  '🥣': MoreIcon,
  '🥡': MoreIcon,
  '🥢': MoreIcon,
  '🧂': MoreIcon,
  '⚽': CircleIcon,
  '🏀': CircleIcon,
  '🏈': CircleIcon,
  '⚾': CircleIcon,
  '🥎': CircleIcon,
  '🎾': CircleIcon,
  '🏐': CircleIcon,
  '🏉': CircleIcon,
  '🥏': CircleIcon,
  '🎱': CircleIcon,
  '🪀': CircleIcon,
  '🏓': CircleIcon,
  '🏸': CircleIcon,
  '🏒': CircleIcon,
  '🏑': CircleIcon,
  '🥍': CircleIcon,
  '🏏': CircleIcon,
  '🥅': Target01Icon,
  '⛳': Target01Icon,
  '🛹': PlayIcon,
  '🛼': Rotate01Icon,
  '🛷': Rocket01Icon,
  '⛸️': CircleIcon,
  '🥌': CircleIcon,
  '⛷️': TriangleIcon,
  '🏂': TriangleIcon,
  '🏋️': ThumbsUpIcon,
  '🤼': UserGroupIcon,
  '🤸': UserIcon,
  '⛹️': CircleIcon,
  '🤺': Target01Icon,
  '🤾': CircleIcon,
  '🏌️': Target01Icon,
  '🏇': UserIcon,
  '🧘': UserIcon,
  '🏄': WaveIcon,
  '🏊': WaveIcon,
  '🤽': WaveIcon,
  '🚣': WaveIcon,
  '🧗': ArrowUp01Icon,
  '🚵': Rotate01Icon,
  '🚴': Rotate01Icon,
  '🏆': Medal01Icon,
  '🥇': Medal01Icon,
  '🥈': Medal01Icon,
  '🥉': Medal01Icon,
  '🏅': Medal01Icon,
  '🎖️': Medal01Icon,
  '🎗️': Medal01Icon,
  '🎟️': PlayIcon,
  '🎫': PlayIcon,
  '🎮': PlayIcon,
  '🕹️': PlayIcon,
  '🎲': DiamondIcon,
  '♟️': CircleIcon,
  '🎯': Target01Icon,
  '🎳': CircleIcon,
  '🎪': PartyIcon,
  '🎭': AiBeautifyIcon,
  '🎨': AiBeautifyIcon,
  '🎬': Film01Icon,
  '🎤': AiMicIcon,
  '🎧': VolumeHighIcon,
  '🎼': MusicNote01Icon,
  '🎵': MusicNote01Icon,
  '🎶': MusicNote01Icon,
  '🎷': MusicNote01Icon,
  '🎸': MusicNote01Icon,
  '🎺': MusicNote01Icon,
  '🎻': MusicNote01Icon,
  '🥁': MusicNote01Icon,
  '🎹': MusicNote01Icon,
  '🎽': CircleIcon,
  '🎿': TriangleIcon,
  '🛡️': Shield01Icon,
  '🥊': CircleIcon,
  '🦿': ArrowUp01Icon,
  '🦾': ThumbsUpIcon,
  '🤿': WaveIcon,
  '🎣': MoreIcon,
  '🪝': MoreIcon,
  '🪃': Rotate01Icon,
  '🧗‍♀️': ArrowUp01Icon,
  '🧗‍♂️': ArrowUp01Icon,
  '🏌️‍♀️': Target01Icon,
  '🏌️‍♂️': Target01Icon,
  '🏄‍♀️': WaveIcon,
  '🏄‍♂️': WaveIcon,
  '🏊‍♀️': WaveIcon,
  '🏊‍♂️': WaveIcon,
  '🤽‍♀️': WaveIcon,
  '🤽‍♂️': WaveIcon,
  '🚣‍♀️': WaveIcon,
  '🚣‍♂️': WaveIcon,
  '🧘‍♀️': UserIcon,
  '🧘‍♂️': UserIcon,
}

/** 根据 emoji 字符返回对应的 Hugeicons 图标组件 */
export function emojiToIcon(emoji: string): IconSvgElement | undefined {
  return EMOJI_ICON_MAP[emoji]
}

export function EmojiIcon({
  emoji,
  size = 16,
  strokeWidth = 2,
  className,
  style,
}: {
  emoji: string
  size?: number
  strokeWidth?: number
  className?: string
  style?: React.CSSProperties
}) {
  if (emoji === '🦞') {
    return <LobsterIcon size={size} className={className} />
  }
  const icon = EMOJI_ICON_MAP[emoji]
  return (
    <HugeiconsIcon
      icon={icon ?? SquareIcon}
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={{ verticalAlign: 'middle', ...style }}
    />
  )
}
